version: '3.8'
services:
    postgres:
        image: postgres:latest
        restart: always
        user: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        healthcheck:
           test: ["CMD-SHELL", "pg_isready -U postgres"]
           interval: 1s
           timeout: 10s
           retries: 3
           start_period: 0s
        ports:
          - '5438:5432'
        volumes: 
          - postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          #- ./init/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  postgres-data:
          driver: local