version: '3.8'
services:
  postgres_db:
        image: postgres:latest
        restart: always
        user: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5440:5432'
        networks:
          - app-tier
        healthcheck:
           test: ["CMD-SHELL", "pg_isready"]
           interval: 1s
           timeout: 10s
           retries: 3
           start_period: 0s

  python_app:
    build: .
    stdin_open: true
    tty: true
    depends_on:
       postgres_db:
        condition: service_healthy
    networks:
      - app-tier
    volumes:
      - ./data:/bigdata/data
networks:
  app-tier:
    driver: bridge
volumes:
  data:
    driver: local